definitions:
  models.CreateWalletRequest:
    properties:
      userID:
        type: string
    type: object
  models.CreateWalletResponse:
    properties:
      message:
        type: string
      userID:
        type: string
    type: object
  models.TransactionRequest:
    properties:
      amount:
        type: number
      transactionID:
        type: string
      transactionType:
        type: string
      userID:
        type: string
    type: object
  models.TransactionResponse:
    properties:
      message:
        type: string
      userID:
        type: string
    type: object
  models.Wallet:
    properties:
      balance:
        type: number
      id:
        type: string
      userID:
        type: string
      walletVersion:
        type: integer
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check the health status of the service.
      operationId: health-check
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Health Check
  /users/{id}/wallet:
    get:
      consumes:
      - application/json
      description: Get wallet details for the specified user ID.
      operationId: get-wallet
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Wallet'
      summary: Get Wallet
  /users/wallet:
    post:
      consumes:
      - application/json
      description: Create a wallet for the specified user ID.
      operationId: create-wallet
      parameters:
      - description: Create Wallet Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateWalletRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CreateWalletResponse'
      summary: Create a Wallet
  /users/wallet/add:
    post:
      consumes:
      - application/json
      description: Add funds to the wallet for the specified user ID.
      operationId: add-funds
      parameters:
      - description: Transaction Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransactionResponse'
      summary: Add Funds to Wallet
  /users/wallet/remove:
    post:
      consumes:
      - application/json
      description: Remove funds from the wallet for the specified user ID.
      operationId: remove-funds
      parameters:
      - description: Transaction Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TransactionResponse'
      summary: Remove Funds from Wallet
swagger: "2.0"
